### ISSUE TITLE
Placement doesn't check all tiles for larger traps.

### ISSUE THREAD

**Issue by vfarias** [rikhardsvensson/StortSpel-Grupp1#53] opened 2016-02-15 13:50 UTC
Some traps occupy more than one tilespace. All those spaces should be on a placeable tile before the trap can be placed.

**Comment by NordicGamer** [comment] 2016-02-19 22:02
Now TeslaCoil's active area is checked if IsPlaceable.

I53-Check-Large-Traps

f6bbbf0fe83930d9126749fcd5cfc4a37a0fe922

**Comment by NordicGamer** [comment] 2016-02-22 10:20
I53-Check-Large-Traps Don't work as intended.
Someone fix this that have a good idea.

**Comment by rikhardsvensson** [comment] 2016-03-02 23:30
Fixed in 6a859025f15040bd62dadfe428a5f0fe52d94849

**Closed as completed by rikhardsvensson** 2016-03-02 23:30 UTC
